### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by jasonwhite**
`syscalls` was updated to fix a build issue.

### CODE REVIEW

**Comment by wangbj** [comment]
Should *Cargo.lock* be checked in? I thought we should only check in *Cargo.toml*, what do you think?

**Comment by jasonwhite** [comment]
Yes it should be checked in for binaries, but not libraries. In this case, `Cargo.lock` is used to build `reverie` the binary.

**Comment by wangbj** [comment]
Hmm, it seems `rustfmt` has `Cargo.lock` checked in while `clippy` doesn’t: https://github.com/rust-lang/rust-clippy. Unless there’s a good reason I’d prefer not to check in `Cargo.lock`

**Comment by rrnewton** [comment]
Without cargo.lock how can you guarantee that any particular CI execution is reproducible in the future?

We might not care, as CI has a transient nature.  But it seems like we should get in the habit of following the philosophy of reproducible workflows based on immutable data.

**Comment by jasonwhite** [comment]
I think clippy is a special case: https://github.com/rust-lang/rust-clippy/issues/1019#issuecomment-420619499

As @rrnewton said, the main reason to commit `Cargo.lock` is for reproducible builds. (`Cargo.lock` is already in reverie btw.)

**Pull request merged**
